# 02 Image Captioning

- Implement image captioning
- Uses BLIP to generate captions from input images

## Setup

In [ ]:
# Install required libraries
!pip install pandas transformers gTTS torch torchvision pillow

Collecting pandas
  Using cached pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting transformers
  Downloading transformers-5.6.2-py3-none-any.whl.metadata (33 kB)
Collecting gTTS
  Using cached gTTS-2.5.4-py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: torch in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (2.11.0)
Requirement already satisfied: torchvision in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (0.26.0)
Requirement already satisfied: numpy>=2.3.3 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from pandas) (2.9.0.post0)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Using cached huggingface_hub-1.11.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: packaging>=20.0 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from transformers) (26.1)
Requirement already satisfied: pyyaml>=5.1 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from transformers) (6.0.3)
Collecting regex>=2025.10.22 (from transformers)
  Using cached regex-2026.4.4-cp314-cp314-macosx_11_0_arm64.whl.metadata (40 kB)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers)
  Using cached tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl.metadata (7.3 kB)
Collecting typer (from transformers)
  Downloading typer-0.24.2-py3-none-any.whl.metadata (15 kB)
Collecting safetensors>=0.4.3 (from transformers)
  Using cached safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl.metadata (4.1 kB)
Collecting tqdm>=4.27 (from transformers)
  Using cached tqdm-4.67.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: filelock>=3.10.0 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.0)
Requirement already satisfied: fsspec>=2023.5.0 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.3.0)
Collecting hf-xet<2.0.0,>=1.4.3 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached hf_xet-1.4.3-cp37-abi3-macosx_11_0_arm64.whl.metadata (4.9 kB)
Collecting httpx<1,>=0.23.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached httpx-0.28.1-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Collecting anyio (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached anyio-4.13.0-py3-none-any.whl.metadata (4.5 kB)
Requirement already satisfied: certifi in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.4.22)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached httpcore-1.0.9-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: idna in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.13)
Collecting h11>=0.16 (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached h11-0.16.0-py3-none-any.whl.metadata (8.3 kB)
Requirement already satisfied: requests<3,>=2.27 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from gTTS) (2.33.1)
Collecting click<8.2,>=7.1 (from gTTS)
  Using cached click-8.1.8-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from requests<3,>=2.27->gTTS) (3.4.7)
Requirement already satisfied: urllib3<3,>=1.26 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from requests<3,>=2.27->gTTS) (2.6.3)
Requirement already satisfied: setuptools<82 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from torch) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from torch) (3.1.6)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from torchvision) (12.2.0)
Requirement already satisfied: six>=1.5 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from jinja2->torch) (3.0.3)
INFO: pip is looking at multiple versions of typer to determine which version is compatible with other requirements. This could take a while.
Collecting typer (from transformers)
  Using cached typer-0.24.1-py3-none-any.whl.metadata (16 kB)
  Using cached typer-0.24.0-py3-none-any.whl.metadata (16 kB)
  Using cached typer-0.23.2-py3-none-any.whl.metadata (16 kB)
  Using cached typer-0.23.1-py3-none-any.whl.metadata (16 kB)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=10.11.0 (from typer->transformers)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.11.0->typer->transformers)
  Using cached markdown_it_py-4.0.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Users/birat/Desktop/COM3025-CW/.venv/lib/python3.14/site-packages (from rich>=10.11.0->typer->transformers) (2.20.0)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
Downloading transformers-5.6.2-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 22.8 MB/s  0:00:00eta 0:00:01
Using cached huggingface_hub-1.11.0-py3-none-any.whl (645 kB)
Using cached hf_xet-1.4.3-cp37-abi3-macosx_11_0_arm64.whl (3.6 MB)
Using cached httpx-0.28.1-py3-none-any.whl (73 kB)
Using cached httpcore-1.0.9-py3-none-any.whl (78 kB)
Using cached tokenizers-0.22.2-cp39-abi3-macosx_11_0_arm64.whl (3.0 MB)
Using cached gTTS-2.5.4-py3-none-any.whl (29 kB)
Using cached click-8.1.8-py3-none-any.whl (98 kB)
Using cached h11-0.16.0-py3-none-any.whl (37 kB)
Using cached regex-2026.4.4-cp314-cp314-macosx_11_0_arm64.whl (289 kB)
Using cached safetensors-0.7.0-cp38-abi3-macosx_11_0_arm64.whl (447 kB)
Using cached tqdm-4.67.3-py3-none-any.whl (78 kB)
Using cached anyio-4.13.0-py3-none-any.whl (114 kB)
Using cached typer-0.23.1-py3-none-any.whl (56 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: tqdm, shellingham, safetensors, regex, mdurl, hf-xet, h11, click, anyio, annotated-doc, pandas, markdown-it-py, httpcore, gTTS, rich, httpx, typer, huggingface-hub, tokenizers, transformers
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20/20 [transformers][0m [transformers]ub]
Successfully installed annotated-doc-0.0.4 anyio-4.13.0 click-8.1.8 gTTS-2.5.4 h11-0.16.0 hf-xet-1.4.3 httpcore-1.0.9 httpx-0.28.1 huggingface-hub-1.11.0 markdown-it-py-4.0.0 mdurl-0.1.2 pandas-3.0.2 regex-2026.4.4 rich-15.0.0 safetensors-0.7.0 shellingham-1.5.4 tokenizers-0.22.2 tqdm-4.67.3 transformers-5.6.2 typer-0.23.1

## Generate captions

In [1]:
import torch
from pathlib import Path
from PIL import Image
import pandas as pd
from transformers import BlipProcessor, BlipForConditionalGeneration

# Paths
images_dir = Path("../data/coco_test")
output_dir = Path("../results/captions")
output_dir.mkdir(parents=True, exist_ok=True)

# Device
device = "cuda" if torch.cuda.is_available() else "cpu"

# Load processor and model
processor = BlipProcessor.from_pretrained("Salesforce/blip-image-captioning-base")
model = BlipForConditionalGeneration.from_pretrained("Salesforce/blip-image-captioning-base").to(device)

# Load image files
image_files = sorted([f for f in images_dir.iterdir() if f.suffix.lower() in ['.jpg']])

# Generate caption for an image
def generate_caption(image_path, max_new_tokens=20):
    image = Image.open(image_path).convert("RGB")
    inputs = processor(images=image, return_tensors="pt").to(device)
    outputs = model.generate(**inputs, max_new_tokens=max_new_tokens)
    caption = processor.decode(outputs[0], skip_special_tokens=True)
    return caption

results = []
for image_file in image_files:
    try:
        caption = generate_caption(image_file)
        results.append({
            "image": image_file.name,
            "caption": caption
        })
        print(f"{image_file.name}: {caption}")
    except Exception as e:
        results.append({
            "image": image_file.name,
            "caption": None,
            "error": str(e)
        })

captions_df = pd.DataFrame(results)
captions_df.to_csv(output_dir / "blip_captions.csv", index=False)

captions_df.head()

/Users/manumalakannavar/Documents/COM3025-CW/COM3025_Virtual_Env/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
Loading weights: 100%|██████████| 473/473 [00:00<00:00, 66015.77it/s]

000000000139.jpg: a living room with a television and a fireplace
000000000285.jpg: a brown bear sitting in the grass
000000000632.jpg: a bedroom with a bed and a window
000000000724.jpg: a stop sign on a street corner
000000000776.jpg: a brown teddy bear
000000000785.jpg: a woman in a red jacket skiing down a hill
000000000802.jpg: a kitchen with a white refrigerator and a white stove
000000000872.jpg: a man in a baseball uniform
000000000885.jpg: a man playing tennis
000000001000.jpg: a group of kids
000000001268.jpg: a woman taking a picture of a swan
000000001296.jpg: a woman holding a cell phone
000000001353.jpg: a group of people riding on a red train
000000001425.jpg: a plate with a sandwich on it
000000001490.jpg: a man on a surfboard
000000001503.jpg: a white desk
000000001532.jpg: a freeway with a bunch of cars driving underneath
000000001584.jpg: a red double decker bus driving down a street
000000001675.jpg: a black and white cat sitting on a computer
000000001761.jpg: a bridge over the water
000000001818.jpg: a zebra eating grass
000000001993.jpg: a bedroom with a bed and a table
000000002006.jpg: a purple bus is driving down the street
000000002149.jpg: a bowl of green apples sitting on a table
000000002153.jpg: a baseball player swinging at a ball during a game
000000002157.jpg: a red table cloth
000000002261.jpg: a man in the water
000000002299.jpg: a group of children
000000002431.jpg: a plate with a knife and a bowl of food
000000002473.jpg: a person jumping in the air on skis
000000002532.jpg: a person on skis on a snowy slope
000000002587.jpg: a banana and a banana in a bag
000000002592.jpg: a knife and a mug on a table
000000002685.jpg: a group of people standing around a kitchen
000000002923.jpg: a field of tall grass
000000003156.jpg: a man sitting on a toilet
000000003255.jpg: a group of people skiing down a snowy mountain
000000003501.jpg: a bowl of rice and broccote
000000003553.jpg: a person is skateboarding on a wooden ramp
000000003661.jpg: a bunch of bananas
000000003845.jpg: a plate of food on a table
000000003934.jpg: a woman and a child playing with a remote
000000004134.jpg: two men shaking hands
000000004395.jpg: a man in a white shirt and tie
000000004495.jpg: a living room with a couch and a television
000000004765.jpg: a man on a surfboard
000000004795.jpg: a cat sitting on a desk next to a laptop
000000005001.jpg: a group of people
000000005037.jpg: a bus on the road
000000005060.jpg: a man sitting on the floor taking a picture of himself

              image                                          caption
0  000000000139.jpg  a living room with a television and a fireplace
1  000000000285.jpg                a brown bear sitting in the grass
2  000000000632.jpg                a bedroom with a bed and a window
3  000000000724.jpg                   a stop sign on a street corner
4  000000000776.jpg                               a brown teddy bear

## Generate audio files

In [2]:
from pathlib import Path
from gtts import gTTS

# Audio Path
audio_dir = Path("../results/audio")
audio_dir.mkdir(parents=True, exist_ok=True)

# Convert captions to audio
def caption_to_audio(caption, output_path):
    tts = gTTS(text=caption, lang='en', slow=False)
    tts.save(output_path)

audio_results = []
for idx, row in captions_df.iterrows():
    image = row['image']
    caption = row['caption']

    # Skip if caption is missing
    if pd.isna(caption):
        continue

    audio_file_name = Path(image).stem + ".mp3"
    audio_path = audio_dir / audio_file_name

    try:
        caption_to_audio(caption, audio_path)

        audio_results.append({
            "image": image,
            "caption": caption,
            "audio": audio_file_name
        })

        print(f"Created audio for {image}: {audio_file_name}")
    except Exception as e:
        audio_results.append({
            "image": image,
            "caption": caption,
            "audio": None,
            "error": str(e)
        })

audio_df = pd.DataFrame(audio_results)
audio_df.to_csv(output_dir / "audio_results.csv", index=False)
audio_df.head()

Created audio for 000000000139.jpg: 000000000139.mp3
Created audio for 000000000285.jpg: 000000000285.mp3
Created audio for 000000000632.jpg: 000000000632.mp3
Created audio for 000000000724.jpg: 000000000724.mp3
Created audio for 000000000776.jpg: 000000000776.mp3
Created audio for 000000000785.jpg: 000000000785.mp3
Created audio for 000000000802.jpg: 000000000802.mp3
Created audio for 000000000872.jpg: 000000000872.mp3
Created audio for 000000000885.jpg: 000000000885.mp3
Created audio for 000000001000.jpg: 000000001000.mp3
Created audio for 000000001268.jpg: 000000001268.mp3
Created audio for 000000001296.jpg: 000000001296.mp3
Created audio for 000000001353.jpg: 000000001353.mp3
Created audio for 000000001425.jpg: 000000001425.mp3
Created audio for 000000001490.jpg: 000000001490.mp3
Created audio for 000000001503.jpg: 000000001503.mp3
Created audio for 000000001532.jpg: 000000001532.mp3
Created audio for 000000001584.jpg: 000000001584.mp3
Created audio for 000000001675.jpg: 000000001675.mp3
Created audio for 000000001761.jpg: 000000001761.mp3
Created audio for 000000001818.jpg: 000000001818.mp3
Created audio for 000000001993.jpg: 000000001993.mp3
Created audio for 000000002006.jpg: 000000002006.mp3
Created audio for 000000002149.jpg: 000000002149.mp3
Created audio for 000000002153.jpg: 000000002153.mp3
Created audio for 000000002157.jpg: 000000002157.mp3
Created audio for 000000002261.jpg: 000000002261.mp3
Created audio for 000000002299.jpg: 000000002299.mp3
Created audio for 000000002431.jpg: 000000002431.mp3
Created audio for 000000002473.jpg: 000000002473.mp3
Created audio for 000000002532.jpg: 000000002532.mp3
Created audio for 000000002587.jpg: 000000002587.mp3
Created audio for 000000002592.jpg: 000000002592.mp3
Created audio for 000000002685.jpg: 000000002685.mp3
Created audio for 000000002923.jpg: 000000002923.mp3
Created audio for 000000003156.jpg: 000000003156.mp3
Created audio for 000000003255.jpg: 000000003255.mp3
Created audio for 000000003501.jpg: 000000003501.mp3
Created audio for 000000003553.jpg: 000000003553.mp3
Created audio for 000000003661.jpg: 000000003661.mp3
Created audio for 000000003845.jpg: 000000003845.mp3
Created audio for 000000003934.jpg: 000000003934.mp3
Created audio for 000000004134.jpg: 000000004134.mp3
Created audio for 000000004395.jpg: 000000004395.mp3
Created audio for 000000004495.jpg: 000000004495.mp3
Created audio for 000000004765.jpg: 000000004765.mp3
Created audio for 000000004795.jpg: 000000004795.mp3
Created audio for 000000005001.jpg: 000000005001.mp3
Created audio for 000000005037.jpg: 000000005037.mp3
Created audio for 000000005060.jpg: 000000005060.mp3

,image,caption,audio
0,000000000139.jpg,a living room with a television and a fireplace,000000000139.mp3
1,000000000285.jpg,a brown bear sitting in the grass,000000000285.mp3
2,000000000632.jpg,a bedroom with a bed and a window,000000000632.mp3
3,000000000724.jpg,a stop sign on a street corner,000000000724.mp3
4,000000000776.jpg,a brown teddy bear,000000000776.mp3